import os

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_API_URL = f"{OLLAMA_BASE_URL}/api/generate"
OLLAMA_TAGS_URL = f"{OLLAMA_BASE_URL}/api/tags"

TIMEOUT_CONNECTION = 5
TIMEOUT_GENERATION = 300
TIMEOUT_EXTRACTION = 120

DEFAULT_COVERAGE_PERCENT = 80
DEFAULT_LLM_CHUNK_SIZE = 8000
DEFAULT_SPACY_BATCH_SIZE = 100000
DEFAULT_SEED = 42