from spacy.lang.ru.stop_words import STOP_WORDS as STOPWORDS

TECH_TERMS = {
    # ── Аббревиатуры / протоколы / стандарты
    "api", "gpu", "cpu", "tpu", "npu", "fpga", "asic",
    "ram", "rom", "ssd", "hdd", "nvme",
    "sql", "nosql", "newsql",
    "html", "css", "json", "xml", "yaml", "toml", "csv", "parquet", "avro", "protobuf",
    "http", "https", "http2", "http3", "websocket", "ws", "wss",
    "rest", "graphql", "grpc", "soap", "rpc", "jsonrpc",
    "crud", "orm", "odm", "mvc", "mvvm", "mvp",
    "cli", "gui", "tui", "repl",
    "sdk", "ide", "git", "svn",
    "ci", "cd", "cicd",
    "tcp", "udp", "ip", "dns", "dhcp", "ssh", "ssl", "tls",
    "ftp", "sftp", "smtp", "imap", "pop3",
    "jwt", "oauth", "oauth2", "oidc", "saml", "sso", "mfa", "2fa",
    "uuid", "uri", "url", "urn",
    "ascii", "utf8", "unicode",
    "cors", "csrf", "xss", "sqli",
    "acid", "cap", "base",
    "oltp", "olap", "etl", "elt",
    "cdn", "vpn", "vps", "vpc", "vpc", "nat", "elb", "alb",
    "iac", "sla", "slo", "sli",
    "poc", "mvp", "rfp", "rfc",
    "iot", "ar", "vr", "xr",

    # ── ML / AI / DL 
    "ml", "ai", "dl", "rl", "drl",
    "nlp", "nlu", "nlg", "cv", "asr", "tts", "ocr",
    "cnn", "rnn", "lstm", "gru", "gan", "vae", "wgan",
    "bert", "gpt", "gpt2", "gpt3", "gpt4", "llm", "slm", "vlm", "mllm",
    "t5", "bart", "roberta", "distilbert", "xlnet", "electra", "deberta",
    "clip", "dall-e", "dalle", "stablediffusion", "midjourney",
    "whisper", "codex",
    "rag", "lora", "qlora", "peft", "sft", "rlhf", "dpo", "ppo", "grpo",
    "adapter", "prefix-tuning", "prompt-tuning", "ia3",
    "moe", "mixture-of-experts",
    "transformer", "attention", "self-attention", "cross-attention", "multi-head-attention",
    "embedding", "tokenizer", "tokenization", "bpe", "wordpiece", "sentencepiece",
    "encoder", "decoder", "autoencoder", "seq2seq",
    "batch", "minibatch", "epoch", "iteration", "step",
    "dropout", "batchnorm", "layernorm", "rmsnorm", "groupnorm",
    "softmax", "relu", "gelu", "silu", "swish", "leaky-relu", "elu", "tanh", "sigmoid", "mish",
    "backpropagation", "backprop", "gradient", "gradient-descent", "sgd", "adam", "adamw",
    "adagrad", "rmsprop", "learning-rate", "lr", "warmup", "cosine-annealing",
    "scheduler", "optimizer", "loss", "cross-entropy", "mse", "mae", "bce",
    "regularization", "l1", "l2", "weight-decay", "early-stopping",
    "fine-tuning", "finetuning", "pretraining", "pre-training",
    "inference", "training", "evaluation", "validation",
    "overfitting", "underfitting", "generalization",
    "dataset", "dataloader", "data-augmentation", "augmentation",
    "benchmark", "baseline", "sota", "state-of-the-art",
    "accuracy", "precision", "recall", "f1", "f1-score",
    "auc", "roc", "roc-auc", "pr-curve",
    "bleu", "rouge", "meteor", "perplexity", "ppl",
    "map", "iou", "dice", "cosine-similarity",
    "confusion-matrix", "classification", "regression", "clustering", "segmentation",
    "detection", "recognition", "generation", "summarization", "translation",
    "quantization", "pruning", "distillation", "knowledge-distillation",
    "int8", "int4", "fp16", "bf16", "fp32", "fp8", "mixed-precision",
    "onnx", "tensorrt", "openvino", "triton",
    "sharding", "parallelism", "data-parallelism", "model-parallelism", "tensor-parallelism",
    "pipeline-parallelism", "deepspeed", "fsdp", "megatron", "zero",
    "flash-attention", "flashattention",
    "hyperparameter", "grid-search", "random-search", "bayesian-optimization",
    "automl", "nas", "neural-architecture-search",
    "feature-engineering", "feature-extraction", "feature-selection",
    "dimensionality-reduction", "pca", "tsne", "umap",
    "random-forest", "decision-tree", "gradient-boosting", "xgboost", "lightgbm", "catboost",
    "svm", "knn", "k-means", "dbscan",
    "logistic-regression", "linear-regression",
    "naive-bayes", "bagging", "boosting", "ensemble",
    "cross-validation", "k-fold", "stratified",
    "reinforcement-learning", "q-learning", "policy-gradient",
    "reward-model", "reward-shaping", "environment", "agent",
    "diffusion", "score-matching", "flow-matching", "normalizing-flow",
    "contrastive-learning", "self-supervised", "semi-supervised", "unsupervised", "supervised",
    "few-shot", "zero-shot", "one-shot", "in-context-learning", "chain-of-thought", "cot",
    "prompt", "prompting", "prompt-engineering",
    "hallucination", "grounding", "alignment", "safety",
    "token", "context-window", "context-length",
    "vit", "resnet", "efficientnet", "yolo", "unet", "mobilenet",
    "word2vec", "glove", "fasttext", "elmo",
    "ner", "pos-tagging", "dependency-parsing", "coreference",
    "beam-search", "greedy-decoding", "top-k", "top-p", "temperature", "nucleus-sampling",
    "speculative-decoding", "kv-cache",

    # ── MLOps / Data Engineering 
    "mlops", "dataops", "aiops", "llmops",
    "mlflow", "wandb", "weights-and-biases", "neptune", "comet",
    "dvc", "feast", "feature-store",
    "airflow", "dagster", "prefect", "luigi", "kubeflow",
    "spark", "pyspark", "hadoop", "mapreduce", "hive", "presto", "trino",
    "dbt", "fivetran", "airbyte",
    "data-lake", "data-warehouse", "data-mesh", "data-lakehouse",
    "delta-lake", "iceberg", "hudi",
    "snowflake", "bigquery", "redshift", "databricks",
    "model-registry", "model-serving", "model-monitoring",
    "a/b-testing", "ab-testing", "canary", "blue-green",
    "feature-flag", "experiment-tracking",

    # ── Инфраструктура / DevOps / Cloud
    "docker", "dockerfile", "docker-compose", "podman", "containerd",
    "kubernetes", "k8s", "k3s", "helm", "kustomize",
    "istio", "envoy", "service-mesh", "sidecar",
    "linux", "ubuntu", "debian", "centos", "alpine", "rhel",
    "nginx", "apache", "caddy", "traefik", "haproxy",
    "aws", "azure", "gcp", "digitalocean", "hetzner", "yandex-cloud",
    "ec2", "s3", "lambda", "ecs", "eks", "fargate", "sagemaker",
    "cloudformation", "cdk", "terraform", "pulumi", "ansible", "chef", "puppet",
    "vagrant", "packer",
    "microservice", "microservices", "monolith", "modular-monolith",
    "container", "containerization", "orchestration",
    "devops", "devsecops", "sre", "platform-engineering",
    "monitoring", "logging", "tracing", "observability",
    "prometheus", "grafana", "loki", "jaeger", "zipkin", "datadog", "newrelic", "elk",
    "logstash", "kibana", "fluentd", "fluentbit",
    "load-balancer", "reverse-proxy", "api-gateway",
    "kong", "apigee", "tyk",
    "vault", "consul", "etcd", "zookeeper",
    "serverless", "faas", "baas", "paas", "iaas", "saas",
    "cron", "systemd", "supervisord",
    "ci/cd", "jenkins", "github-actions", "gitlab-ci", "circleci", "travis",
    "argocd", "fluxcd", "tekton", "spinnaker",
    "sonarqube", "snyk", "trivy",

    # ── Языки программирования 
    "python", "java", "javascript", "typescript", "golang", "go", "rust",
    "c", "c++", "cpp", "c#", "csharp", "dotnet",
    "kotlin", "scala", "swift", "objective-c",
    "ruby", "php", "perl", "r", "julia", "matlab",
    "haskell", "erlang", "elixir", "clojure", "lisp",
    "lua", "dart", "zig", "nim", "mojo",
    "bash", "shell", "powershell",
    "solidity", "wasm", "webassembly",
    "sql", "plpgsql", "tsql",
    "cython", "numba",

    # ── Фреймворки и библиотеки 
    # Web frontend
    "react", "reactjs", "nextjs", "next.js", "remix",
    "vue", "vuejs", "nuxt", "nuxtjs",
    "angular", "angularjs", "svelte", "sveltekit",
    "astro", "gatsby", "eleventy",
    "tailwind", "tailwindcss", "bootstrap", "material-ui", "chakra-ui",
    "webpack", "vite", "esbuild", "rollup", "parcel", "turbopack",
    "babel", "eslint", "prettier",
    "storybook", "cypress", "playwright", "puppeteer", "selenium",
    # Web backend
    "django", "flask", "fastapi", "starlette", "sanic", "aiohttp",
    "express", "expressjs", "nestjs", "koa", "hono", "fastify",
    "spring", "springboot", "spring-boot", "quarkus", "micronaut",
    "rails", "ruby-on-rails", "sinatra",
    "laravel", "symfony",
    "gin", "echo", "fiber",
    "actix", "axum", "rocket",
    "asp.net", "blazor",
    # Python data/ML
    "pytorch", "tensorflow", "keras", "jax", "flax",
    "numpy", "pandas", "polars", "dask", "vaex", "modin",
    "scipy", "scikit-learn", "sklearn", "statsmodels",
    "matplotlib", "seaborn", "plotly", "bokeh", "altair",
    "opencv", "pillow", "imageio",
    "spacy", "nltk", "gensim", "stanza",
    "huggingface", "transformers", "diffusers", "accelerate", "datasets", "tokenizers",
    "langchain", "langsmith", "langgraph",
    "llamaindex", "llama-index", "haystack", "semantic-kernel",
    "openai", "anthropic", "cohere", "replicate",
    "vllm", "tgi", "llama-cpp", "ollama", "lmstudio",
    "gradio", "streamlit", "chainlit", "panel",
    "pydantic", "marshmallow",
    "celery", "dramatiq", "rq",
    "sqlalchemy", "alembic", "tortoise-orm", "peewee",
    "asyncio", "uvicorn", "gunicorn", "hypercorn",
    "pytest", "unittest", "tox", "nox", "coverage",
    "poetry", "pip", "conda", "mamba", "pipenv", "uv", "rye",
    "black", "ruff", "mypy", "pylint", "flake8", "isort",
    # Mobile
    "flutter", "react-native", "swiftui", "jetpack-compose", "xamarin",
    # Desktop
    "electron", "tauri", "qt", "gtk", "tkinter",
    # Game
    "unity", "unreal", "godot",

    # ── Базы данных / хранилища 
    # Реляционные
    "postgresql", "postgres", "mysql", "mariadb", "sqlite",
    "oracle", "mssql", "sql-server", "cockroachdb", "tidb", "yugabyte",
    # Документные / NoSQL
    "mongodb", "couchdb", "couchbase", "dynamodb", "firestore", "cosmosdb",
    # Key-value / кэш
    "redis", "memcached", "valkey", "dragonfly",
    # Колоночные
    "clickhouse", "cassandra", "scylla", "hbase",
    # Поисковые
    "elasticsearch", "opensearch", "solr", "meilisearch", "typesense", "algolia",
    # Векторные
    "pinecone", "weaviate", "milvus", "qdrant", "chroma", "chromadb",
    "pgvector", "faiss", "annoy", "scann",
    # Графовые
    "neo4j", "arangodb", "dgraph", "neptune", "janusgraph",
    # Временные ряды
    "influxdb", "timescaledb", "victoriametrics",
    # Очереди / стриминг
    "kafka", "rabbitmq", "pulsar", "nats", "activemq", "zeromq",
    "kinesis", "sqs", "sns",
    # Object storage
    "minio",

    # ── Архитектура / паттерны / методологии 
    "frontend", "backend", "fullstack", "full-stack",
    "framework", "library", "package", "module",
    "repository", "repo", "monorepo",
    "design-pattern", "solid", "dry", "kiss", "yagni",
    "singleton", "factory", "observer", "strategy", "decorator", "proxy", "facade",
    "dependency-injection", "inversion-of-control", "ioc",
    "event-driven", "event-sourcing", "cqrs",
    "domain-driven-design", "ddd", "hexagonal", "clean-architecture", "onion-architecture",
    "saga", "choreography", "orchestration",
    "pub/sub", "pubsub", "message-queue", "message-broker",
    "webhook", "callback", "polling", "long-polling", "sse",
    "idempotency", "eventual-consistency", "strong-consistency",
    "sharding", "replication", "partitioning",
    "horizontal-scaling", "vertical-scaling", "autoscaling",
    "caching", "cache-invalidation", "ttl",
    "rate-limiting", "throttling", "circuit-breaker", "retry", "backoff",
    "distributed-system", "consensus", "raft", "paxos",
    "twelve-factor", "12-factor",
    "agile", "scrum", "kanban", "lean", "waterfall",
    "tdd", "bdd", "ddd", "atdd",
    "unit-test", "integration-test", "e2e-test", "end-to-end",
    "mocking", "stubbing", "fixture",
    "refactoring", "code-review", "pair-programming", "mob-programming",
    "gitflow", "trunk-based",
    "semver", "semantic-versioning",

    # ── Безопасность
    "encryption", "decryption", "hashing", "salt", "pepper",
    "aes", "rsa", "sha256", "sha512", "md5", "bcrypt", "argon2",
    "firewall", "waf", "ids", "ips",
    "penetration-testing", "pentest", "vulnerability", "exploit",
    "owasp", "cve", "zero-day",
    "rbac", "abac", "acl",
    "certificate", "pki", "x509",
    "sandbox", "isolation",

    # ── Сети / Веб
    "ipv4", "ipv6", "subnet", "cidr",
    "domain", "subdomain", "cname", "a-record", "mx-record",
    "proxy", "socks", "forward-proxy",
    "latency", "throughput", "bandwidth",
    "tcp/ip", "osi-model",
    "webrtc", "quic", "grpc-web",
    "pwa", "spa", "ssr", "ssg", "isr", "csr",
    "seo", "accessibility", "a11y", "i18n", "l10n",
    "responsive", "mobile-first",

    # ── Blockchain / Web3
    "blockchain", "smart-contract", "defi", "nft",
    "ethereum", "bitcoin", "web3",

    # ── Misc / Buzzwords 
    "open-source", "oss", "foss",
    "low-code", "no-code",
    "edge-computing", "fog-computing",
    "digital-twin", "metaverse",
    "ci/cd-pipeline", "pipeline", "workflow", "dag",
    "config", "configuration", "env", "environment-variable",
    "debug", "debugger", "profiler", "profiling", "linter", "formatter",
    "compilation", "runtime", "bytecode", "jit", "aot",
    "concurrency", "parallelism", "multithreading", "multiprocessing",
    "async", "await", "coroutine", "goroutine", "green-thread",
    "mutex", "semaphore", "deadlock", "race-condition",
    "heap", "stack", "garbage-collection", "gc",
    "pointer", "reference", "ownership", "borrowing",
    "generic", "template", "metaclass", "reflection", "introspection",
    "serialization", "deserialization", "marshalling",
    "middleware", "plugin", "extension", "hook",
    "migration", "schema", "index", "query", "transaction",
    "normalization", "denormalization",
    "ascii-art", "regex", "regexp",
    "cron-job", "daemon", "worker", "consumer", "producer",
    "payload", "header", "cookie", "session",
    "pagination", "cursor", "offset",
    "singleton", "prototype", "immutable", "mutable",
    "version-control", "vcs", "branching", "merging", "rebasing",
    "changelog", "roadmap", "backlog", "sprint", "epic", "user-story",
    "documentation", "readme", "wiki",
    "api-key", "secret", "credential", "token",
    "upstream", "downstream", "sidecar",
    "vendor-lock-in", "interoperability", "backward-compatibility",
    "scalability", "reliability", "availability", "resilience", "fault-tolerance",
    "chaos-engineering", "disaster-recovery", "failover", "redundancy",
    "technical-debt", "tech-debt", "legacy",
    "bandwidth", "bottleneck", "hotfix", "patch",
    "deploy", "deployment", "release", "rollback", "rollout",
    "staging", "production", "development", "sandbox",
    "localhost", "port", "socket", "endpoint",
    "payload", "schema-registry",
    "synthetic-data", "data-labeling", "annotation",
    "active-learning", "curriculum-learning",
    "federated-learning", "differential-privacy",
    "explainability", "interpretability", "xai", "shap", "lime",
    "drift", "data-drift", "model-drift", "concept-drift",
}


GARBAGE_PATTERNS = [
    r'^\d+$', r'^\d+\s*[\.\)]\s*\w', r'^\w+\s+\d+$', r'^\d+\s+\w+$',
    r'^стр\.?\s*\d+', r'^\[\d+\]', r'^\(\d+\)', r'^рис\.?\s*\d+', r'^табл\.?\s*\d+',
    r'может$|должен$|является$', r'^(более|менее|очень|весьма)\s',
]